### ISSUE TITLE
在主页的时候会显示滚动条

### ISSUE THREAD

**Issue by JerrellF** [letiantian/huno#34]
![image](https://cloud.githubusercontent.com/assets/8141300/17866437/13908192-68d9-11e6-86c1-4b761f39d173.png)

虽然这个地方是把窗口拉小了才这样，但是post比较多的时候正常的窗口大小也会这样子了，感觉非常难看，希望让滚动条仅在博客页面展开之后显示。

这个问题好像在原版的uno上就有，找了很多port发现只有这一个没有问题：https://github.com/Kikobeats/uno-zen 。本来想自己修但发现还是不太会的样子，希望能帮忙修复一下啦。

**Comment by letiantian** [comment]
你先试着自己改一下吧 我最近不一定有时间。
