### ISSUE TITLE
Hope to support youyan

### ISSUE THREAD

**Issue by TaoCHEN92** [letiantian/huno#40]
As Duoshuo will be no longer available since 2017.07.01, I hope that you can add a script for youyan, Thx

**Comment by Sixdes** [comment]
I'm sorry to bother, I also hope that you can add a script for youyan or changyan.

**Comment by TaoCHEN92** [comment]
@Sixdes Actually you can DIY it。 example:   www.cccttt.me

**Comment by Sixdes** [comment]
@TaoCHEN92 thx

**Comment by ToSeven** [comment]
@TaoCHEN92 按照你的方法 插件模块没有显示出来啊 然后看了下你的网站 你的也没有显示出来。。。

**Comment by letiantian** [comment]
更新了该项目，评论系统的支持更通用了。

将评论系统（例如Disqus、多说、友言、畅言等）提供的代码片段粘贴在layout/_partials/comments.js中即可。

**Comment by TaoCHEN92** [comment]
@ToSeven 是友言服务器崩了，我换成'来比力'了，方法还是一样的
