### ISSUE TITLE
关于自己设定的问题

### ISSUE THREAD

**Issue by ZhangYuAFA** [letiantian/huno#51]
我想在网页加一个背景音乐，用的是audio标签，让后我把这个标签加在本地的网站首页文件里面，因为我想每次部署到网页时都可以有，可是当我部署上去后又恢复了。
请问这个怎么解决？谢谢！

**Comment by letiantian** [comment]
应为网页代码会基于模板生成。所以在网页代码里加内容会被覆盖。在模板合适的地方加上就行了。

**Comment by ZhangYuAFA** [comment]
模板，是指从github克隆的地方吗
