### ISSUE TITLE
许可协议?

### ISSUE THREAD

**Issue by Riband** [letiantian/huno#53]
该项目的许可协议是什么?没有找到

**Comment by letiantian** [comment]
无协议，随便用吧。https://github.com/daleanthony/uno/ 也没指明协议。

**Comment by Riband** [comment]
uno 用的 Creative Commons Attribution 4.0 International 协议( README.md License项) :)

**Comment by Riband** [comment]
还是加一个协议吧，我们这些使用者也舒心 :)

**Comment by letiantian** [comment]
OK
