### ISSUE TITLE
awesome-toc不加载

### ISSUE THREAD

**Issue by penghubingzhou** [letiantian/huno#57]
我不清楚是什么原因，但是我的awesome-toc无法加载出来。从html文档里面可以看到awesome-toc.ejs读取了，而且在手机端有概率可能出现awesome-toc，但是在电脑端永远无法显示。

**Comment by penghubingzhou** [comment]
经过本人仔细对比了awesome-toc的示例源码以及主题的源码并反复测试后，我在awesome-toc的ejs上做了一点小改动来保证其正常加载。详情请见#1，如果没有问题还请作者尽快合并我提交的PR。谢谢！！！

**Comment by letiantian** [comment]
感谢！
