### ISSUE TITLE
awesome-toc在手机端无法显示目录

### ISSUE THREAD

**Issue by penghubingzhou** [letiantian/huno#59]
这个问题有一点诡异，也是遗留问题。awesome-toc在我的手机端目前无法显示目录，点击按钮无响应（手机是苹果的，因为按钮是正常加载的，所以我猜测是主题设置问题，因而在这提问，如果后期发现是脚本问题我就去脚本那提交PR）。如果是脚本本身就没有提供这个功能，还请作者跟我说一下，谢谢~

**Comment by penghubingzhou** [comment]
经过实地测试，此功能可在手机端开启。我制作了一个PR发送到了awesome-toc下，详情见[这里]（https://github.com/letiantian/awesome-toc/pull/2）。以我博客为例的测试结果如下：
![img_0601](https://user-images.githubusercontent.com/40651890/51089391-3eaccc80-17a7-11e9-976a-9913e21ba67f.PNG)

**Comment by letiantian** [comment]
代码有点问题。

**Comment by penghubingzhou** [comment]
> 代码有点问题。

你是说pr的代码？

**Comment by penghubingzhou** [comment]
> 代码有点问题。

新代码已经提交，详情见https://github.com/letiantian/awesome-toc/pull/3

**Comment by penghubingzhou** [comment]
代码已合并到那个项目，应该可以尽早同步到主题下。这个问题我先关闭了。
